### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by mondiedmond** [opengento/magento2-country-store#1]
Hi there! I want to ask if there is a method to create a popup to select the country for the first time when an user enters on site. Thank you!

**Comment by thomas-kl1** [comment]
Hi @mondiedmond 

Yes this is already implemented in https://github.com/opengento/magento2-country-store-switcher
There is a setting to enable a dialog on first visit for the customer, so they can choose their country of preference.

**Comment by mondiedmond** [comment]
Thank you, but my problem is with the php version. I use magento 2.2.6 (php 71) with the old country-switcher module and your new version requirements is php 7.4

**Comment by thomas-kl1** [comment]
Hey, can you shoot me an email at thomasklein876@gmail.com ?

**Comment by asantarissy** [comment]
@thomas-kl1 can I use this in magneto 2.3.6 with php 7.3 ?

**Comment by thomas-kl1** [comment]
@asantarissy Hi, this package is only available for php ^7.4
